import os

BOT_TOKEN = os.getenv("BOT_TOKEN")
REPLICATE_API_TOKEN = os.getenv("REPLICATE_API_TOKEN")
CASHERA_API_KEY = os.getenv("CASHERA_API_KEY")
CASHERA_SHOP_ID = os.getenv("CASHERA_SHOP_ID", "")
CASHERA_WEBHOOK_SECRET = os.getenv("CASHERA_WEBHOOK_SECRET", "")
VIP_PRICE_RUB = 350
FREE_LIMIT = 2